### ISSUE TITLE
Failed to query latest round.

### ISSUE THREAD

**Issue by eavesmy** [oasisprotocol/oasis-web3-gateway#203]
When i start web3-gateway i can see this:

```
{"caller":"grpc.go:242","err":"roothash: block not found","level":"error","method":"/oasis-core.RuntimeClient/GetBlock","module":"grpc/client","msg":"request failed","req_seq":1,"rsp":{"header":{"version":0,"namespace":"0000000000000000000000000000000000000000000000000000000000000000","round":0,"timestamp":"1970-01-01T00:00:00Z","header_type":0,"previous_hash":"0000000000000000000000000000000000000000000000000000000000000000","io_root":"0000000000000000000000000000000000000000000000000000000000000000","state_root":"0000000000000000000000000000000000000000000000000000000000000000","messages_hash":"0000000000000000000000000000000000000000000000000000000000000000","in_msgs_hash":"0000000000000000000000000000000000000000000000000000000000000000"}},"ts":"2022-03-04T11:20:53.76871872Z"}
{"caller":"indexer.go:204","err":"roothash: block not found","level":"info","module":"gateway/indexer","msg":"failed to query latest round","runtime_id":"000000000000000000000000000000000000000000000000e2eaa99fc008f87f","ts":"2022-03-04T11:20:53.768965678Z"}
{"caller":"grpc.go:242","err":"roothash: block not found","level":"error","method":"/oasis-core.RuntimeClient/GetBlock","module":"grpc/client","msg":"request failed","req_seq":2,"rsp":{"header":{"version":0,"namespace":"0000000000000000000000000000000000000000000000000000000000000000","round":0,"timestamp":"1970-01-01T00:00:00Z","header_type":0,"previous_hash":"0000000000000000000000000000000000000000000000000000000000000000","io_root":"0000000000000000000000000000000000000000000000000000000000000000","state_root":"0000000000000000000000000000000000000000000000000000000000000000","messages_hash":"0000000000000000000000000000000000000000000000000000000000000000","in_msgs_hash":"0000000000000000000000000000000000000000000000000000000000000000"}},"ts":"2022-03-04T11:20:54.769550444Z"}
{"caller":"indexer.go:204","err":"roothash: block not found","level":"info","module":"gateway/indexer","msg":"failed to query latest round","runtime_id":"000000000000000000000000000000000000000000000000e2eaa99fc008f87f","ts":"2022-03-04T11:20:54.769629281Z"}
```

What's the situation made this error? What can i do to made me emerald-web3-gateway operating normally?

#### emerald-web3-gateway Build from main branch

**Comment by eavesmy** [comment]
Here is my config.yml:

**Comment by eavesmy** [comment]
Here is my config.yml:
```yml
runtime_id: "000000000000000000000000000000000000000000000000e2eaa99fc008f87f"
node_address: "unix:/data/data/internal.sock"
enable_pruning: false
pruning_step: 100000

log:
  level: debug
  format: json

database:
  host: 127.0.0.1
  port: 5432
  db: oasis
  user: postgres
  password: 6488151d0386848a7f0f2fcd182c35b9
  dial_timeout: 5
  read_timeout: 10
  write_timeout: 5
  max_open_conns: 100

gateway:
  chain_id: 42262
  http:
    host: 0.0.0.0
    port: 9933
    cors: ["*"]
  ws:
    host: 0.0.0.0
    port: 9944
    origins: ["*"]
  method_limits:
    get_logs_max_rounds: 100
```
