### ISSUE TITLE
mkvs: version not found

### ISSUE THREAD

**Issue by eavesmy** [oasisprotocol/oasis-web3-gateway#204]
Block index stoped at round 73.
```
{"caller":"grpc.go:242","err":"mkvs: version not found: transaction: get transactions failed: worker/storage: SyncIterate to local storage failed: mkvs: version not found","level":"error","method":"/oasis-core.RuntimeClient/GetTransactionsWithResults","module":"grpc/client","msg":"request failed","req_seq":1365,"rsp":null,"ts":"2022-03-08T03:15:03.555987314Z"}
```

### emerald-web3-gateway version
```
emerald-web3-gateway --version
Software version: 1.3.1
Oasis SDK version: v0.1.1-0.20220223135638-61574136102a
Go toolchain version: go1.17.7
```

### oasis-node version
```
Software version: 21.3.9
Consensus:
  Consensus protocol version: 4.0.0
Runtime:
  Host protocol version:      4.0.0
  Committee protocol version: 3.0.0
Go toolchain version: 1.16.13
```

### oasis-node config
```yml
datadir: /data/data

log:
  level:
    default: info
    tendermint: info
    tendermint/context: error
  format: JSON

genesis:
  file: /data/etc/genesis.json

consensus:
  tendermint:
    p2p:
      seed:
        - E27F6B7A350B4CC2B48A6CBE94B0A02B0DCB0BF3@35.199.49.168:26656

runtime:
  supported:
    - 000000000000000000000000000000000000000000000000e2eaa99fc008f87f

  paths:
    000000000000000000000000000000000000000000000000e2eaa99fc008f87f: /data/bin/emerald-paratime

worker:
  registration:
    entity: /data/entity/entity.json

  storage:
    enabled: true
    checkpoint_sync:
      disabled: true
  sentry:
    grpc:
      enabled: true
```

### emerald-web3-gateway config
```yml
node_address: "unix:/data/data/internal.sock"
enable_pruning: false
pruning_step: 100000

log:
  level: debug
  format: json

database:
  host: 127.0.0.1
  port: 5432
  db: oasis
  user: postgres
  password: 6488151d0386848a7f0f2fcd182c35b9
  dial_timeout: 5
  read_timeout: 10
  write_timeout: 5
  max_open_conns: 100

gateway:
  chain_id: 42262
  http:
    host: 0.0.0.0
    port: 9933
    cors: ["*"]
  ws:
    host: 0.0.0.0
    port: 9944
    origins: ["*"]
  method_limits:
    get_logs_max_rounds: 100
```

oasis-node control status:
```
{
  "software_version": "21.3.9",
  "identity": {
    "node": "wgJyG7nkJx0IWPjm0Nxkq3WjrUSHciE/HbgYbUOb3Oc=",
    "p2p": "q2R1D5ouFNeuzGO8deMuA3M35s3fr6m6IZLpVwfQyrA=",
    "consensus": "mGbudj/JAmI2og4UmT0dzndqV9nfjtaR/0T7xGBSayY=",
    "tls": [
      "eT01CjBFBzRsHxWgTEfs3r6+JSALEUCOqA8Xw66qSKk=",
      "9tyVpYB3EftM7DBBLz3p7mrEFFRp1xdrKLFNswb8uUY="
    ]
  },
  "consensus": {
    "version": {
      "major": 4
    },
    "backend": "tendermint",
    "features": 3,
    "node_peers": [
      "4b09be0737402c8bc3bfce0424e0e082e4e8c207@23.88.56.166:26656",
      "462dc40e72a895c054b885a6777c8eb609fe0169@35.245.249.189:26656",
      "95a0bc4268dfc30d6880282a046303bb29c48773@88.99.215.94:35656",
      "02ce03a5ca029baa84a8cb00d9866846f18147c0@3.22.73.115:26656",
      "ed79e9d9395ad9a5349a59c26b9810a2dda59223@52.159.79.124:26656",
      "3e5c6ae956cf079f4158dfd130b9b5d3308d1a33@91.90.179.51:26656",
      "e9d0043539e5cb96ec06983858a23643b00c7cb2@35.227.53.250:26656",
      "a815a9a8facbec215feb52e97a089d8f8bc9d6b1@95.217.62.249:27000",
      "a79be979abf98fd3cb6492e90c59e1d90f3f63f5@51.254.124.65:26656",
      "ad3426f93a99683a2a91c5c77d244789e8b98a6d@148.251.91.50:26656",
      "473471e88834740d23f303f32ae12cd6e3a787f9@18.141.53.133:26656",
      "c49f4d99d62510178c6c00d1d5f3050e82aa6955@52.162.156.55:26656",
      "e527309ff618bfc41904bbb93317781aaccefd1a@95.217.62.146:26656",
      "8504291b8717e59cfa44b913857b42ecf584eb3d@195.201.170.254:26656",
      "dd0d0ae872577c53a2a5e5886d2df1dec08e3311@141.94.130.89:26656",
      "ab1c02310d7249cafa1fd53d034e4228bfc4cc72@95.217.74.107:26656",
      "4956a5204eb8ca7b8d2c41292ff26a2883c2be75@174.138.3.116:26656",
      "d8b549e447292d1b36987a70836e0b59e3b75121@54.208.50.80:26656",
      "769dba1b272137aeba189589a254a4254b6220fe@194.233.73.154:26656",
      "cecc03b0e2e21ccb9ac92444608a4c6ca7e5be62@88.99.100.32:26656"
    ],
    "latest_height": 6064409,
    "latest_hash": "ea31a44ab65d82f5b610048d9463eecfd62db0e0a16f1d2fb59902a120083e0e",
    "latest_time": "2021-11-24T09:52:26Z",
    "latest_epoch": 10099,
    "latest_state_root": {
      "ns": "0000000000000000000000000000000000000000000000000000000000000000",
      "version": 6064408,
      "root_type": 1,
      "hash": "7015e84a3cd2d25e09fcb69dce727f97dca238d0207acf3d0e24b7a1c6c37adb"
    },
    "genesis_height": 3027601,
    "genesis_hash": "67045351274dc3d5be3703cfd4ec6e1b58441d19dd96f5df0cea502c4f6d95f4",
    "last_retained_height": 3027601,
    "last_retained_hash": "67045351274dc3d5be3703cfd4ec6e1b58441d19dd96f5df0cea502c4f6d95f4",
    "chain_context": "53852332637bacb61b91b6411ab4095168ba02a50be4c3f82448438826f23898",
    "is_validator": false
  },
  "runtimes": {
    "000000000000000000000000000000000000000000000000e2eaa99fc008f87f": {
      "descriptor": null,
      "latest_round": 342,
      "latest_hash": "5066247b830a2e1679e9eab3eeec09b6f2069ad865d1acbef23cc4ab1985b9ea",
      "latest_time": "2021-11-24T08:58:02Z",
      "latest_state_root": {
        "ns": "000000000000000000000000000000000000000000000000e2eaa99fc008f87f",
        "version": 342,
        "root_type": 1,
        "hash": "6c44d42ae05d6f3d019764f737548e2a3d44b2b98cc1e8c90423648bf46638d0"
      },
      "genesis_round": 0,
      "genesis_hash": "34a5ce9b2ff76fa7b062ceabb5f64d451761c72b8443445b0c9df693d067b5c1",
      "last_retained_round": 0,
      "last_retained_hash": "34a5ce9b2ff76fa7b062ceabb5f64d451761c72b8443445b0c9df693d067b5c1",
      "committee": {
        "latest_round": 0,
        "latest_height": 0,
        "last_committee_update_height": 0,
        "executor_roles": null,
        "storage_roles": null,
        "is_txn_scheduler": false,
        "peers": [
          "/ip4/95.216.25.173/tcp/40002/p2p/12D3KooWT2HEn17eHdkhVq7igY2uoLA2k7vT6ccosfKNM4fcHdQF",
          "/ip4/94.130.34.15/tcp/45002/p2p/12D3KooWF76yZj3NpLw24qLFABvs3n7eaM2aFyAoT7a4isGLV1mq",
          "/ip4/88.99.215.94/tcp/35002/p2p/12D3KooWJzgmDUt5v5XUSdbyb2AHnVfjQnCkKfevzuhmoK38CFNQ",
          "/ip4/54.203.41.63/tcp/30002/p2p/12D3KooWDjvLwGspDSANLvwZGuoPPhMuUqfDKBtnqWqPwZDZZMve",
          "/ip4/172.31.18.97/tcp/30002/p2p/12D3KooWAkKBfHtD5wTXTSMA4oJHi8mFVXfBydmFBQ9UzJas6M7X",
          "/ip4/95.217.62.249/tcp/40002/p2p/12D3KooWEnHPNLM1Cfw9jK8ktYA1KVsaV5BKXLsU6bci8btzfg95",
          "/ip4/80.64.208.65/tcp/30002/p2p/12D3KooWG1P4iJX2mqPUJF3bREgVjb2t9ezMULm1YmKkjTWpEUhH",
          "/ip4/131.153.99.14/tcp/30002/p2p/12D3KooWKPMS72iRgPDWczMVzKyYa3DSZmc771XDNXnMWVPnjfmJ",
          "/ip4/95.217.118.121/tcp/10002/p2p/12D3KooWF15NEgUFnh25SzhY2HJ6EdsywUFy4KLCUSN9X4eXhobL",
          "/ip4/135.181.179.38/tcp/10002/p2p/12D3KooWNYpvGHuWr2V1zdLTbaYQXBLysh6gVqSwsmGJgRUqDEtD",
          "/ip4/135.181.1.160/tcp/10002/p2p/12D3KooWK1mkdF77pp3CxK99uR1LfZuUngkgpZ6nEKPHMuk9V1FS",
          "/ip4/51.222.154.19/tcp/30002/p2p/12D3KooWQShu4eMSPDiaWmfVTcpqfKWumBrbcovEo6AznhcUfheN",
          "/ip4/88.99.100.32/tcp/30002/p2p/12D3KooWHcwXSe1cxnGjcyF92A1woBCujFxuUbT5TfcrWMtvAh2k",
          "/ip4/23.88.105.64/tcp/30002/p2p/12D3KooWJzEi7z5bu4EroUBezW3BtygoiSYdWGrr8DqrBdoKA9mP",
          "/ip4/136.243.103.147/tcp/40002/p2p/12D3KooWBizfYwusJJbccD66ZfavAs5Nn2wjb8JF89gC1U9LJD64",
          "/ip4/95.216.37.80/tcp/40002/p2p/12D3KooWPW3yJRiL54Wnz9XirNsDdT66dAJvitKd4EpTZTdTYLh4",
          "/ip4/95.216.241.124/tcp/30002/p2p/12D3KooWSJ4WnjUY76cfiifujynaxD15QnCdQfzxuJsyqzat24rp",
          "/ip4/141.95.35.31/tcp/30002/p2p/12D3KooWCyjYceAstcSNeUXP5dBcLfVaEjb1KzWZKQ343jaVnVQA",
          "/ip4/135.181.130.59/tcp/30002/p2p/12D3KooWDzq86WGEqEHcVCYfhukxuYKPq7cjrCxwsYg5euBpTcfi"
        ]
      },
      "storage": {
        "last_finalized_round": 18446744073709551615
      }
    }
  },
  "registration": {
    "last_registration": "0001-01-01T00:00:00Z"
  },
  "pending_upgrades": []
}
```

It's my config problem?
It confuse me days. Plz help me fix this.
